# Do not edit this file when generating an application.
#
# The image contract - what the Terraform module depends on:
#   - listens on $PORT (default 8000)
#   - runs as a non-root user
#   - GET /health returns 200 without touching the database
#   - started with the single argument `migrate`, applies pending schema
#     migrations and exits 0; the module runs this as an init container
# Changing any of it here breaks deployment in a way that is hard to trace back
# to this file.

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

# Restore first, from the project files and lock files only, so the package
# layer is cached until a dependency actually changes.
COPY global.json Directory.Build.props Directory.Packages.props ./
COPY src/App/App.csproj src/App/packages.lock.json src/App/
RUN dotnet restore src/App/App.csproj --locked-mode

COPY src/ src/
RUN dotnet publish src/App/App.csproj -c Release --no-restore -o /out

# Chiseled: no shell, no package manager, non-root by default. There is
# deliberately no HEALTHCHECK - Container Apps uses its own probes against
# /health, and the image has no curl to run one with.
FROM mcr.microsoft.com/dotnet/aspnet:10.0-noble-chiseled AS runtime
WORKDIR /srv
COPY --from=build /out .

ENV PORT=8000 \
    ASPNETCORE_HTTP_PORTS=
EXPOSE 8000
USER $APP_UID

ENTRYPOINT ["dotnet", "App.dll"]
